# test workflow for testing out everything when a new change is pushed.

name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:18-alpine'
    steps:
    - uses: actions/checkout@v3
    - run: yarn
    - run: yarn test