# test workflow for testing out everything when a new change is pushed.

name: Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: 'node:18-alpine'
    steps:
    - uses: actions/checkout@v3
    - run: yarn
    - run: yarn test
    - name: Load github env secrets
      env:
        INVEST_ENV_FILE: ${{ secrets.INVEST_ENV_FILE }}
      run: |
        echo "${INVEST_ENV_FILE}" >> apps/invest/.env
    - run: yarn run build